### ISSUE TITLE
AWS broker disconnected

### ISSUE THREAD

**Issue by normanmaurer** [sh00t2kill/dolphin-robot#113]
From time to time I see that the AWS broker is disconnected. To fix this I have to restart homeassistant. I wonder if it would be possible to implement some sort of reconnect ?

**Comment by sh00t2kill** [comment]
You dont have to fully restart, you can use the homeassistant.reload_config_entry service, with an entity_id of your vacuum.

That will restart the integration, rather than having to restart all of HA.

The component *does* auto reconnect, but on occasion the reconnect fails.

**Comment by normanmaurer** [comment]
interesting... Maybe you could implement some "reconnect" every X minutes or so... It fails here quite often it seems

**Comment by sh00t2kill** [comment]
most of us using it have an automation running based on when aws drops offline --- but yes its been an ongoing problem

**Comment by elad-bar** [comment]
There is a mechanism that tries to reconnect, hopefully in the upcoming month I will have more time to do a major improvment I planned to improve performance and stability

**Comment by oNaiPs** [comment]
I think this is the same as https://github.com/sh00t2kill/dolphin-robot/issues/97

**Comment by elad-bar** [comment]
To make sure it is like #97 we need logs :), can you please share logs for the disconnections?

Thanks

**Comment by oNaiPs** [comment]
@elad-bar @sh00t2kill here goes an extensive log from several days of using the component. Note that I reloaded it a couple times through the days (when it was not working). It's pretty reproducible, after one or two days of running it gets to this unrecoverable state.

[home-assistant_2023-06-27T08-49-20.632Z.log](https://github.com/sh00t2kill/dolphin-robot/files/11879807/home-assistant_2023-06-27T08-49-20.632Z.log)

**Comment by elad-bar** [comment]
please check  the new release [v0.4.0](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v0.4.0),
It should address the broker disconnection, tested for 4 days without single disconnection.

please let me know if it works for you

thanks

**Comment by oNaiPs** [comment]
@elad-bar just tried v0.4.0f, started by deleting previous integration (i had 2 devices instead of one), and now I cannot past the authentication (username/password) screen:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/mydolphin_plus/config_flow.py", line 37, in async_step_user
await config_manager.initialize()
File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 91, in initialize
await self._load()
File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 126, in _load
if self._entry.entry_id not in self._data:
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'entry_id'
```

**Comment by elad-bar** [comment]
sorry for that, didn't manage to get to the error while testing, currently not at home so I'm releasing fixes without actual test them, I made a deeper review of the code and released new version that should solve it [v0.4.2](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v0.4.2), please test it or wait for an update after I test it later today.

if you tested it anyway, please update whether it solved the problem or not,
thanks

**Comment by msaphoto06** [comment]
> 

Same. Upgrade from 3.3 to 4.1. Duplicate robot. Module removed. I have not been able to log in since. Tested 4.2 and 3.3

**Comment by elad-bar** [comment]
Pls check if you have under .storage directory file with the name mydolphin in it,
If there is please delete it (with v0.4.2), restart HA, and try to add the integration.
Thanks

**Comment by msaphoto06** [comment]
eleted 3 files in .storage
removed the integration.
Installed in 4.2
Unable to connect.
Nothing new in .storage

`Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mydolphin_plus/config_flow.py", line 37, in async_step_user
    await config_manager.initialize()
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 91, in initialize
    await self._load()
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 126, in _load
    if self._entry.entry_id not in self._data:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'entry_id'`

**Comment by elad-bar** [comment]
seems that something is broken with v0.4.2, the error you are presenting includes code from v0.4.1 not latest,
released [v0.4.3](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v0.4.3) (with no code changes) to try solve it .

**Comment by elad-bar** [comment]
@normanmaurer can you pls update if issue solved by [v0.4.4](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v0.4.4)?

thanks

**Comment by elad-bar** [comment]
@normanmaurer is there an update?

Thanks

**Comment by bleughb** [comment]
I'm seeing this regularly now, the M700 rarely stays online two days in a row, anyone else seeing this issue?

**Comment by sh00t2kill** [comment]
Ive seen it more recently of late, yes.
