### ISSUE TITLE
'Unknown error' signing into Mydolphin integration

### ISSUE THREAD

**Issue by MaxVonEvil** [sh00t2kill/dolphin-robot#118]
Hi there, as of yesterday I noticed the integration seems to be broken.
I tried removing it, restart HA and re-added it, however it throws 'Unknown Error when I try to log in with my verified credentials. I've checked the mobile app and it works fine.

Here's the skinny on the HA environment:
Home Assistant 2023.7.1 
Supervisor 2023.07.1 
Operating System 10.3 
Frontend 20230705.1 - latest 

I found the following in the log:
```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/mydolphin_plus/managers/config_manager.py:59
Integration: mydolphin_plus (documentation, issues)
First occurred: 19:00:27 (1 occurrences)
Last logged: 19:00:27

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 297, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mydolphin_plus/config_flow.py", line 37, in async_step_user
    await config_manager.initialize()
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 104, in initialize
    await self._load()
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 134, in _load
    await self._load_encryption_key()
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 149, in _load_encryption_key
    if self.data is None:
       ^^^^^^^^^
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 59, in data
    return self._data.get(self._entry_id)
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

```

Hope this helps to solve it

**Comment by elad-bar** [comment]
Which version of integration is installed?

Thanks

**Comment by joeyjojo747** [comment]
Im getting the same.
Was version 4.3. Rolled back to 4.1 and same issue.

**Comment by MaxVonEvil** [comment]
Hi Elad, right now no version as it can't register, however it's the most
recent available

**Comment by elad-bar** [comment]
I have fix for it [PR 119](https://github.com/sh00t2kill/dolphin-robot/pull/119), but didn't test it yet, will get to it later today and release new version

**Comment by MaxVonEvil** [comment]
Sounds good, I'm on Pacific time and will look out for it tomorrow.

**Comment by elad-bar** [comment]
Tested the new version for 3 hours with almost any possible flow I manage to think,
Please test version [v0.4.4](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v0.4.4) and report how it worked for you,
please read the changelog for that version as it might introduce breaking change,
I tried to minimize as possible the chance to get to it, but in case something went wrong with the previous versions in your config, it might happen as well, 
for that added a section in troubleshooting (and changelog) of how to solve it - spoiler, in worst case scenario, you will need to delete a configuration file of the integration and add the integration again.

**Comment by espeir** [comment]
v0.4.4 worked for me this morning.  I had already deleted the integration (last night).

**Comment by MaxVonEvil** [comment]
Same here, working again. Thanks @elad-bar for the quick fix!

**Comment by elad-bar** [comment]
great, @MaxVonEvil can you pls close this issue?

thanks

**Comment by MaxVonEvil** [comment]
I'll be happy to if I can, yet tbh I've not done that before as it's
normally something the owner of the repo can do. I'll have a look at it
tomorrow if it's still open

**Comment by elad-bar** [comment]
I will close it if that's ok, normally I don't like to close issues without making sure it's ok with the opener

thanks
