### ISSUE TITLE
Integration not loading after Updating HASS to 2024.1.0

### ISSUE THREAD

**Issue by cRemE-fReSh** [sh00t2kill/dolphin-robot#165]
First of all a happy new year!

After upgrading HASS to the newest version, the integration does not load any more:

![grafik](https://github.com/sh00t2kill/dolphin-robot/assets/42785404/48fae29c-30db-4e40-b7b0-f491ca9b0c33)

Detailed logs for both fault messages:

**Logger: homeassistant.loader
Source: loader.py:822
First occurred: 13:30:33 (1 occurrences)
Last logged: 13:30:33**

Unexpected exception importing component custom_components.mydolphin_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/mydolphin_plus/__init__.py", line 14, in <module>
    from .managers.config_manager import ConfigManager
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 28, in <module>
    from ..common.entity_descriptions import MyDolphinPlusEntityDescription
  File "/config/custom_components/mydolphin_plus/common/entity_descriptions.py", line 76, in <module>
    @dataclass(slots=True)
     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'entity_category' follows default argument

**Logger: homeassistant.setup
Source: setup.py:251
First occurred: 13:30:33 (1 occurrences)
Last logged: 13:30:33**

Setup failed for custom integration 'mydolphin_plus': Unable to import component: Exception importing custom_components.mydolphin_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/mydolphin_plus/__init__.py", line 14, in <module>
    from .managers.config_manager import ConfigManager
  File "/config/custom_components/mydolphin_plus/managers/config_manager.py", line 28, in <module>
    from ..common.entity_descriptions import MyDolphinPlusEntityDescription
  File "/config/custom_components/mydolphin_plus/common/entity_descriptions.py", line 76, in <module>
    @dataclass(slots=True)
     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'entity_category' follows default argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 830, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.mydolphin_plus

Any idea how to fix that?

Best regards!

**Comment by sh00t2kill** [comment]
Have you also upgraded the integration to the latest version?
1.0.8?

**Comment by cRemE-fReSh** [comment]
@sh00t2kill Sorry! My fault. I haven't seen the update in HACS yet.
No more issues after updating to the newest version.
