### ISSUE TITLE
Cannot install integration

### ISSUE THREAD

**Issue by whiskas85** [sh00t2kill/dolphin-robot#230]
When I:
 - Go to setting
 - Device and integration
 - Add new integration

It popup mi this screen that never install the component
![image](https://github.com/user-attachments/assets/2c7a32c8-e912-403b-8458-1b9c50d346b4)

At the end I recieve this message:
![image](https://github.com/user-attachments/assets/a5d3d933-3e30-447a-a97c-4a9693c22335)

and Home assisistant will reboot atuomatically (it crashes badly)

**Comment by whiskas85** [comment]
Home assistant is installed into a Raspberry PI 3B

**Comment by elad-bar** [comment]
Logs pls

**Comment by whiskas85** [comment]
Hi,
I tried to install it at 17.22.
At 17.25 the home assistant crashed and restarted.
At 17.29 system fully restarted.

Let me know if you need other type of logs




Il giorno mar 30 lug 2024 alle ore 15:59 Elad Bar ***@***.***>
ha scritto:

**Comment by whiskas85** [comment]
I retried it and the installation failed, but the system didn't restart.
The log contains an interesting detail


Il giorno mar 30 lug 2024 alle ore 17:31 Marco Allario <
***@***.***> ha scritto:

**Comment by elad-bar** [comment]
Without logs I can't understand the issue, what you have described is chain of events which is not helping to debug

**Comment by whiskas85** [comment]
I attached all the logs to the previous email

Il giorno mar 30 lug 2024 alle ore 17:55 Elad Bar ***@***.***>
ha scritto:

**Comment by whiskas85** [comment]
[home-assistant (1).log](https://github.com/user-attachments/files/16430915/home-assistant.1.log)

**Comment by whiskas85** [comment]
I am trying to reinstall MyDolphin

2024-07-30 21:06:24.748 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/mydolphin_plus/__init__.py', 'wb') inside the event loop by custom integration 'hacs' at custom_components/hacs/repositories/base.py, line 698: zip_file.extractall(self.content.path.local, extractable) (offender: /usr/local/lib/python3.12/zipfile/__init__.py, line 1801: open(targetpath, "wb") as target:), please create a bug report at https://github.com/hacs/integration/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 977, in async_install_repository
    await self.download_content(version_to_install)
  File "/config/custom_components/hacs/repositories/base.py", line 628, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 698, in download_repository_zip
    zip_file.extractall(self.content.path.local, extractable)


This happens after HACS automatica installation

**Comment by whiskas85** [comment]
With the "automatic" HACS installation it's not possible to install SW becuase it's not installing required dependencies.

![image](https://github.com/user-attachments/assets/7fd35ec9-5c16-4110-9052-3471c8b8be53)

**Comment by whiskas85** [comment]
I think I found the issue. 
By trying to install it manually, I installed the requirements.txt and i get this error.

![image](https://github.com/user-attachments/assets/2b844cee-2541-4340-b07a-132042e72aac)

**Comment by whiskas85** [comment]
![image](https://github.com/user-attachments/assets/e4ce7b7e-72d7-4cc8-ba8d-36c6b62d76a5)

**Comment by elad-bar** [comment]
Not all requirements are being installed, only those in manifest.json

**Comment by elad-bar** [comment]
any updates?

thanks

**Comment by whiskas85** [comment]
It's not possible to install MyDolphinPlus automatically or manually

Il dom 4 ago 2024, 10:11 Elad Bar ***@***.***> ha scritto:

**Comment by sh00t2kill** [comment]
There was a previous issue raised similar to this some time ago.

I seem to recall a supervisor update being required and then it was all fine. 
This seems to me like an issue with your install and not strictly the integration. It could be a package conflict with another custom integration too.

Have you tried manually installing the packages mentioned in the manifest file?
This should give more info

**Comment by whiskas85** [comment]
I tried to install it manually.
The issue as I reported in the pics is that:
it's required the package homeassistant 2024.5.3 that requires httpx 0.27.x
it's required the package googletrans 4.0 that requires httpx 0.13

So there's no possibility to satisfy both the requirements.

That's why it's not an issue of my installation that is pretty much standard

**Comment by elad-bar** [comment]
did you try to run the pip install just for the packages in the manifest? 
if yes, packages were installed? 
if not, what is the error?
if packages were installed, what is the error in HA?

thanks

**Comment by whiskas85** [comment]
I downloaded requirment.txt
Uploaded on my raspi
run the command for downloading the requirement and attached the message before:
https://github.com/sh00t2kill/dolphin-robot/issues/230#issuecomment-2259071381
the error I got.

I cannot add all the packages because there is a problem on dependencies.
There is all the process documented with screenshot the messages before

**Comment by sh00t2kill** [comment]
Don't use the requirements file, that's for use outside of ha so it will fail.
Try manually installing the single package mentioned in manifest.json.

Ie awsiotsdk

How do you have HA installed?

**Comment by whiskas85** [comment]
I have HA installed into RaspBerry stando alone (without docker).

Running commanad 
pip install awsiotsdk I get this:

![image](https://github.com/user-attachments/assets/a5c7c3dc-2d92-4563-a1d9-80f7a16f6374)

**Comment by sh00t2kill** [comment]
Cmake is missing. This is the exact same issue the other person had.

Maybe supervisor needs to be updated

**Comment by sh00t2kill** [comment]
Where are you running that? It's not clear from your screenshot, however cmake missing was the exact issue the other user had.
